!!python/object:argparse.Namespace
capacity: 1000
climate_mean_init: 1.0
climate_period: 10
env_type: combined
init_SD: 0.1
model: hybrid
mutate: 0.005
num_agents: 1000
num_gens: 6000
num_trials: 2
project: Maslin/debug_conf
scale_time: 1
