!!python/object:argparse.Namespace
capacity: 1000
climate_mean_init: 1.0
climate_period: 10
env_type: combined
init_SD: 0.1
model: D
mutate: 0.001
num_agents: 1000
num_gens: 5000
project: Maslin/modelD_r0.001
scale_time: 1
